# Dockerfile for image tagged model_ramp_bootstrap:1

FROM tensorflow/tensorflow:2.8.2

WORKDIR /tf

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gdal-bin \
        libgdal-dev \
        python3-opencv && \
    mkdir -p \
        data/input/images \
        data/input/checkpoint \
        data/output && \
    pip install --upgrade pip && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

COPY . .

# TODO: optimize RUN commands
RUN pip install . && \
    pip install solaris/

ENV RAMP_HOME=/tf

CMD ["/tf/run_model.sh"]
