# Dockerfile for image tagged model_ramp_bootstrap:1-gpu

# TODO: optimize RUN and COPY commands to minimal number of layers.

FROM tensorflow/tensorflow:2.8.2-gpu

WORKDIR /model
COPY . .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

ENTRYPOINT [ "bash", "run_model.sh" ]
